
$(document).ready(
    function()
    {
        $("#button1").click(function()
        {
           $("#dip_comp_sci").slideToggle();
        }); 
        $("#button2").click(function()
        {
            $("#free_eng_aca").slideToggle();
        });
        $("#button3").click(function()
        {
            $("#soe").slideToggle();
        });
        $("#button4").click(function()
        {
            $("#tutoraj").slideToggle();
        });
        $("#button5").click(function()
        {
            $("#abhayshala").slideToggle();
        });
    }
);